### ISSUE TITLE
Failed giving version

### ISSUE THREAD

**Issue by waghanza** [crystal-community/msgpack-crystal#24]
Hello,

I use `msgpack` to communicate between my apis.

I have added

``` yaml
  msgpack:
    github: benoist/msgpack-crystal
    version: ~> 0.3
```

into my `shards.yml` but it lead me to an error 

``` crystal
Error resolving msgpack (~> 0.3)
```

Is there a way to precise version (e.g : not to use **master**) ?
Regards,
